### ISSUE TITLE
Plans to support MS Windows (Visual Studio or msys2 toolchain)

### ISSUE THREAD

**Issue by sidec** [nicolasdanet/S#1]
Hi, are there any plans to add support for Windows? As far as I know projucer can export to Visual Studio, unfortunetelly not out of the box to msys2 makefiles, but anyway, it might open project for contributions from devs working on this platform.
Also, is there any platform specific code that would prevent `S` from being portable to MS system?

**Comment by nicolasdanet** [comment]
There is a plan to port Spaghettis to Windows < https://github.com/Spaghettis/Spaghettis/issues/96 >.
The JUCE framework support Windows and platform specific codes that remain could be adapted without too much pain.
The Audio/MIDI backend will be the hardest part as the Spaghettis core uses platform API directly (CoreAudio / Jack).
The only reason why i dropped Windows at first was to mitigate the complexity while refactoring.
Specially since i don't have any Windows machine to test and that i never developped on that platform.
IMHO that port can't be done before the end of the GUI swap (the solely goal of that repository).
I changed (and i will change again) too much things such that merging/synchronizing branches would be a nightmare.
Frankly at first i was not enthusiastic about a Windows port.
I have to buy another computer (and probably another one more to support Apple ARM)!
But since you are the third person to ask me about, i guess it must be done in order to make that project to continue.
It will probably the first things i'll done after achieved the GUI and test a bit more the DSP engine stability.

**Comment by sidec** [comment]
That's a great news indeed. I am not big fan of win10 but stuck on this os. I am not C developer  (I have background in jvm languages and devops) but after trying to write or compile few Pd externals I can attest first hand that switching from linux to win is initially a big pain when comes to compilation and in general project infrastructure. I would suggest you to switch to cmake build system if planning develope for these three os. I heard that  JUCE 6 supports it out of the box. I can provide a feedback/testing after first build is availlable.  Regarding of Audio/Midi backend - are you considering ASIO on Windows through JUCE_ASIO or boost::asio?

**Comment by nicolasdanet** [comment]
It seems that more and more people are switching to CMake on the JUCE forum.
But frankly i'll do it only if i'm forced (i don't want to add extra work wheras there's already so much to do)!
Anyway Spaghettis dependencies are limited to JUCE / and the platform Audio/MIDI backends.
It is not so hard to compile (i really wanted to make it simple to-compile-by-yoursefl).
The core of Spaghettis is supposed to be compilable without any externals libraries.
Fed-up with Tcl/Tk and others....
On macOS i use CoreAudio directly, and on Linux JACK for now (but i would like to use raw ALSA too).
On Windows i have no idea, but if i can i'll do it also by myself.
Anyway i'm not sure at all that the GUI rewrite will end this year!

**Comment by sidec** [comment]
Sure, I understand clearly your objectives and also the amount of work. Do you plan any technical document (or paper) that would help other developers in on-boarding?

**Comment by nicolasdanet** [comment]
I'll not make any documentation or whatever before finishing the GUI.
I can not explain how it is done, since i don't know for now how i'll do it!

I have no idea for the days after. I know that i should communicate more, but at the same time good papers are a lot of work.
Work to be done and also maintained, published... when things changes. Work is doubled.
Same for CI tools / webpages and all that kind of propaganda. 
I'm not a student, i don't care about badges and self-promotion.
And as i'm not paid for that, i'm reluctant to invest some time in something without guaranteed ROI.
Six months ago i was near to definitely stop that project due to a kind of (common into FLOSS) burnout (thanks @jacksongoode).
And now i prefer to spend my time to respond to one human interested, than to try to grab _peoples_ (since they really don't care).

Consequently i'll be more in favor to use [discussions](https://github.com/Spaghettis/Spaghettis/discussions) and others GitHub stuff (or a FAQ) than to make PDF, lightning talks and such. That project is not mature enought. Of course with more human resources my opinion would evolved!

Definitely a too long response for a short question!

**Comment by sidec** [comment]
Thanks, don't have problem with long responses. My only two cents to discussions is that ROI in FOSS depends greatly on how a project is attractive for other devs (also students craving for badges). In this particular case, project is already quite mature, as you has started from already sofisticated code base. Also your goals are really not for a single dev. 
In my opinion it would be great to have software that starts from Pd, improves the same paradigm, has resonable compatability (also atractive for Max/MSP users) but is more up to what is today expected from this kind of software. You are surely aware about how Pd development is governed, so we won't see a lot of progress there apart of maintaing, stability and bug fixes (which is actually great and I don't have a problem with it, and I quite enjoy the fact that it looks and works pretty the same as in 2001 when I started using it). 
Last thing, when comes to CI, I can help.

**Comment by nicolasdanet** [comment]
I"m agree with you.But in practice the energy/time/money left for me is rather limited.
No chance that i could seduce the crowd without an achieved cute GUI. 
It is a reasonable choice to spent my last shot of gazoline into that task, instead of burning it into expensive cocktails.

**Comment by nicolasdanet** [comment]
To be continued : Spaghettis/Spaghettis#96
